version: '3'

services:
  vaultwarden_application:
    restart: always
    container_name: vaultwarden_app
    hostname: vlt_app
    image: vaultwarden/server:latest
    volumes:
      - "./vaultwarden/data/:/data/"
    env_file:
      - vault_app.conf
    depends_on:
      - vaultwarden_database
      - vaultwarden_proxy
    networks:
      vaultwarden-network:
        ipv4_address: 192.168.1.2

  vaultwarden_database:
    image: postgres:15-alpine
    container_name: vaultwarden_db
    hostname: vlt_db
    restart: always
    volumes:
      - "./vaultwarden/postgres/:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - vault_db.conf
    networks:
      vaultwarden-network:
        ipv4_address: 192.168.1.3

  vaultwarden_proxy:
    image: nginx:mainline
    container_name: vaultwarden_prx
    hostname: vlt_prx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3012:3012"
    volumes:
      - ./vaultwarden/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vaultwarden/nginx/sites-available/:/etc/nginx/sites-available
      - ./vaultwarden/nginx/certs/:/etc/nginx/certs
    networks:
      vaultwarden-network:
        ipv4_address: 192.168.1.4
networks:
  vaultwarden-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
